// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace UserDataStore.MySql.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    Type = table.Column<string>(nullable: false),
                    LastDisplayName = table.Column<string>(nullable: true),
                    FirstSeen = table.Column<DateTime>(nullable: true),
                    LastSeen = table.Column<DateTime>(nullable: true),
                    BanInfo_ExpireDate = table.Column<DateTime>(nullable: true),
                    BanInfo_InstigatorType = table.Column<string>(nullable: true),
                    BanInfo_InstigatorId = table.Column<string>(nullable: true),
                    BanInfo_Reason = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => new { x.Id, x.Type });
                });

            migrationBuilder.CreateTable(
                name: "UserGenericDatas",
                columns: table => new
                {
                    Key = table.Column<string>(nullable: false),
                    UserId = table.Column<string>(nullable: false),
                    UserType = table.Column<string>(nullable: false),
                    SerializedValue = table.Column<string>(type: "json", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserGenericDatas", x => new { x.Key, x.UserId, x.UserType });
                    table.ForeignKey(
                        name: "FK_UserGenericDatas_Users_UserId_UserType",
                        columns: x => new { x.UserId, x.UserType },
                        principalTable: "Users",
                        principalColumns: new[] { "Id", "Type" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserGrantedPermissions",
                columns: table => new
                {
                    Permission = table.Column<string>(nullable: false),
                    UserId = table.Column<string>(nullable: false),
                    UserType = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserGrantedPermissions", x => new { x.UserId, x.UserType, x.Permission });
                    table.ForeignKey(
                        name: "FK_UserGrantedPermissions_Users_UserId_UserType",
                        columns: x => new { x.UserId, x.UserType },
                        principalTable: "Users",
                        principalColumns: new[] { "Id", "Type" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserGrantedRoles",
                columns: table => new
                {
                    RoleId = table.Column<string>(nullable: false),
                    UserId = table.Column<string>(nullable: false),
                    UserType = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserGrantedRoles", x => new { x.UserId, x.UserType, x.RoleId });
                    table.ForeignKey(
                        name: "FK_UserGrantedRoles_Users_UserId_UserType",
                        columns: x => new { x.UserId, x.UserType },
                        principalTable: "Users",
                        principalColumns: new[] { "Id", "Type" },
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserGenericDatas_UserId_UserType",
                table: "UserGenericDatas",
                columns: new[] { "UserId", "UserType" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserGenericDatas");

            migrationBuilder.DropTable(
                name: "UserGrantedPermissions");

            migrationBuilder.DropTable(
                name: "UserGrantedRoles");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
